# ----------------------------------------
# Basic site settings
# ----------------------------------------
remote_theme: raviriley/agency-jekyll-theme

url      : "https://www.fhdsa.org"
baseurl  : ""                 # leave empty for root-domain site

title       : "Flint Hills DSA"
email       : "chapter@fhdsa.org"   # contact-form target
description : "Official website for the Flint Hills Chapter of the Democratic Socialists of America"
author      : "Derron Borders"

logo:
  path  : "/assets/img/clients/fhdsalogo.png"
  height: 60

locale: "en-US"

analytics:
  google:    # add tracking ID if you use GA

# ----------------------------------------
# Collections
# ----------------------------------------
collections:
  portfolio:
    output: true
  about:
    output: true
  resources:
    output: true
  documents:                 # external Markdown synced here
    output: true
    permalink: /docs/:path/  # clean URLs like /docs/chapter-documentation/bylaws/

# ----------------------------------------
# Default front-matter for documents
# ----------------------------------------
defaults:
  - scope:
      path: ""               # match any file
      type: documents        # only the documents collection
    values:
      layout : resource
      section: resources

# ----------------------------------------
# Markdown processor
# ----------------------------------------
markdown: kramdown

# ----------------------------------------
# Formspree (contact & modal forms)
# ----------------------------------------
formspree_form_path: "f/xyzwrkba"

# ----------------------------------------
# Plugins (GitHub Pages-allowed only)
# ----------------------------------------
plugins:
  - jekyll-remote-theme
