# ----------------------------------------
# Basic site settings
# ----------------------------------------
remote_theme: raviriley/agency-jekyll-theme

url       : "https://flinthillsdsa.github.io"
baseurl   : ""                 # leave empty for root‐domain site

title       : "Flint Hills DSA"
email       : "chapter@fhdsa.org"
description : "Official website for the Flint Hills Chapter of the Democratic Socialists of America"
author      : "Derron Borders"

logo:
  path  : "/assets/img/clients/fhdsalogo.png"
  height: 60

locale: "en-US"

analytics:
  google:    # add tracking ID if you use GA
  
future: true
# ----------------------------------------
# Collections
# ----------------------------------------
collections:
  portfolio:
    output: true
  about:
    output: true
  resources:
    output: true
    permalink: /resources/:path/

# ----------------------------------------
# Default front‐matter for resources
# ----------------------------------------
defaults:
  - scope:
      path: ""               # every file in the resources collection
      type: resources
    values:
      layout : resource
      section: resources

# ----------------------------------------
# Markdown processor
# ----------------------------------------
markdown: kramdown

# ----------------------------------------
# Formspree (contact & modal forms)
# ----------------------------------------
formspree_form_path: "f/xyzwrkba"

# ----------------------------------------
# Plugins (GitHub Pages–allowed only)
# ----------------------------------------
plugins:
  - jekyll-remote-theme
