name: Post Portfolio Updates to Bluesky

on:
  push:
    branches:
      - main
    paths:
      - '_portfolio/**.md'

jobs:
  post-to-bluesky:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install pyyaml bluesky

      - name: Post to Bluesky
        run: python .github/scripts/post_to_bluesky.py
        env:
          BLUESKY_HANDLE: ${{ secrets.BLUESKY_HANDLE }}
          BLUESKY_PASSWORD: ${{ secrets.BLUESKY_PASSWORD }}
          WEBSITE_URL: "https://www.fhdsa.org"
