name: Post to Bluesky

on:
  push:
    branches:
      - main
    paths:
      - '_portfolio/**.md'

permissions:
  contents: write

jobs:
  post-to-bluesky:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install pyyaml atproto requests

      - name: Run Bluesky post script
        run: python .github/scripts/post_to_bluesky.py
        env:
          BLUESKY_HANDLE: ${{ secrets.BLUESKY_HANDLE }}
          BLUESKY_PASSWORD: ${{ secrets.BLUESKY_PASSWORD }}

      - name: Commit updated .bluesky_posted
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add .bluesky_posted
          git commit -m "Update .bluesky_posted after Bluesky post" || echo "No changes to commit"
          git push
