name: Sync Governing By-laws

permissions:
  contents: write

on:
  workflow_dispatch:            # you can run it manually from “Actions”
  schedule:
    - cron: '0 3 * * 1'         # every Monday 03:00 UTC  (adjust as needed)
  push:
    paths:
      - .github/workflows/sync-governing-doc.yml   # run if you edit the workflow
      - _documents/**                               # or if you change docs manually

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get governing-documents repo
        run: |
          git clone --depth=1 https://github.com/flinthillsdsa/governing-documents tmpgov
          mkdir -p _documents/chapter-documentation
          cp tmpgov/bylaws/2025-05-25-fhdsa-bylaws.md \
             _documents/chapter-documentation/bylaws.md

      # Ensure the file has minimal front-matter so Jekyll renders it
      - name: Add default front-matter if missing
        run: |
          FILE="_documents/chapter-documentation/bylaws.md"
          if ! grep -q '^---' "$FILE"; then
            echo '---'                                >  tmpfile
            echo 'layout: resource'                  >> tmpfile
            echo 'title: "Chapter By-Laws"'          >> tmpfile
            echo 'section: resources'                >> tmpfile
            echo '---'                               >> tmpfile
            cat  "$FILE"                             >> tmpfile
            mv tmpfile "$FILE"
          fi

      - name: Commit & push if changed
        run: |
          git config user.name  "github-actions"
          git config user.email "actions@github.com"
          git add _documents/chapter-documentation/bylaws.md
          git diff --quiet --cached || git commit -m "Sync governing by-laws" && git push
