# 1) Download the file ----------------------------------------------------------------
- name: Download bylaws
  run: |
    mkdir -p _documents/chapter-documentation
    curl -sL \
      https://raw.githubusercontent.com/flinthillsdsa/governing-documents/main/bylaws/2025-05-25-fhdsa-bylaws.md \
      -o _documents/chapter-documentation/bylaws.md

# 2) Extract first heading -> title, strip heading, prepend YAML -----------------------
- name: Inject front-matter
  run: |
    FILE=_documents/chapter-documentation/bylaws.md

    # 2a) Grab first Markdown heading line (e.g. "# Chapter By-Laws")
    FIRST_HEADING=$(grep -m1 -E '^# ' "$FILE" | sed 's/^# *//')
    TITLE=${FIRST_HEADING:-"Document"}          # fallback if none

    # 2b) Remove that first heading line from body
    sed -i '0,/^# /{s/^# .*//}' "$FILE"

    # 2c) Add or replace front-matter
    {
      echo '---'
      echo 'layout: resource'
      echo 'section: resources'
      printf 'title: "%s"\n' "$TITLE"
      # Optional subtitle based on filename
      # printf 'subtitle: "%s"\n' "$(basename "$FILE" .md | tr '-' ' ')"
      echo '---'
      echo
      cat "$FILE"
    } > tmpfile && mv tmpfile "$FILE"
